# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-13 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OdmOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('domain_name', models.CharField(max_length=200)),
                ('locations', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OdmPeople',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locations', models.CharField(max_length=200)),
                ('socials', models.CharField(max_length=200)),
                ('types', models.CharField(max_length=200)),
            ],
        ),
    ]
